CREATE OR REPLACE TEMPORARY TABLE stage_contents AS
        SELECT
            METADATA$FILENAME AS filename, METADATA$FILE_LAST_MODIFIED AS DATE
        FROM '@DB_ODS_BILLING.SH_STAGING_DEVEL.AWS_STAGE_IMPORT_S3_BUCKET_BILLING_SOURCE_DATASETS_ARIA_STG/'
        order by 2 ;


    
CREATE OR REPLACE TEMPORARY TABLE directories2 AS
    SELECT DISTINCT SPLIT_PART(filename, '/', -2) AS directory, *
    FROM stage_contents;

                    
SELECT 'UPDATE  DB_ODS_BILLING.sh_staging_devel.'|| table_name || '
SET DH_LOAD_DATE = DATE FROM  directories2 WHERE directories2.FILENAME = DH_LOAD_FILE  ;' 
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG ='DB_ODS_BILLING'
AND TABLE_SCHEMA = 'SH_STAGING_DEVEL'
AND TABLE_NAME LIKE '%ARIA%';
