-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;




/*
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_PLAN_INSTANCE ADD COLUMN DH_LOAD_FILE_TEMP STRING,  DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_PLAN_INSTANCE
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_PLAN_INSTANCE DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_PLAN_INSTANCE RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE,
DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;


CREATE TABLE SRC_ARIA_PLAN_INSTANCE_REST CLONE SRC_ARIA_PLAN_INSTANCE   AT(TIMESTAMP => 'Wed, 20 NOV 2024 15:40:00 +0300'::timestamp_tz); 



-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_PLAN_INSTANCE ADD COLUMN OVERRIDE_BILL_THRU_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_PLAN_INSTANCE
SET OVERRIDE_BILL_THRU_DATE_TEMP = DATE(OVERRIDE_BILL_THRU_DATE)
WHERE OVERRIDE_BILL_THRU_DATE IS NOT NULL AND OVERRIDE_BILL_THRU_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_PLAN_INSTANCE DROP COLUMN OVERRIDE_BILL_THRU_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_PLAN_INSTANCE RENAME COLUMN OVERRIDE_BILL_THRU_DATE_TEMP TO OVERRIDE_BILL_THRU_DATE;
---------------------


-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN PAID_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET PAID_DATE_TEMP = DATE(PAID_DATE)
WHERE PAID_DATE IS NOT NULL AND PAID_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN PAID_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN PAID_DATE_TEMP TO PAID_DATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_CLIENT_LEGAL_ENTITY
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;


-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY ADD COLUMN UPDATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_CLIENT_LEGAL_ENTITY
SET UPDATE_DATE_TEMP = UPDATE_DATE
WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY DROP COLUMN UPDATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN UPDATE_DATE_TEMP TO UPDATE_DATE;
---------------------



-- Crear nueva columna temporal

ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY ADD COLUMN VAT_REGISTRATION_NO_TEMP VARCHAR;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_CLIENT_LEGAL_ENTITY
SET VAT_REGISTRATION_NO_TEMP = VAT_REGISTRATION_NO
WHERE VAT_REGISTRATION_NO IS NOT NULL AND VAT_REGISTRATION_NO != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY DROP COLUMN VAT_REGISTRATION_NO;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN VAT_REGISTRATION_NO_TEMP TO VAT_REGISTRATION_NO;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY ADD COLUMN REGISTRATION_NO_TEMP VARCHAR;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_CLIENT_LEGAL_ENTITY
SET REGISTRATION_NO_TEMP = REGISTRATION_NO
WHERE REGISTRATION_NO IS NOT NULL AND REGISTRATION_NO != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY DROP COLUMN REGISTRATION_NO;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN REGISTRATION_NO_TEMP TO REGISTRATION_NO;
---------------------


SELECT * FROM SRC_ARIA_CLIENT_LEGAL_ENTITY;

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY ADD COLUMN CREATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_CLIENT_LEGAL_ENTITY
SET CREATE_DATE_TEMP = DATE(CREATE_DATE)
WHERE CREATE_DATE IS NOT NULL AND CREATE_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY DROP COLUMN CREATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_CLIENT_LEGAL_ENTITY RENAME COLUMN CREATE_DATE_TEMP TO CREATE_DATE;
---------------------


-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_TRANSACTION
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;


---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ADD COLUMN FULLY_APPLIED_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_TRANSACTION
SET FULLY_APPLIED_DATE_TEMP = DATE(FULLY_APPLIED_DATE)
WHERE FULLY_APPLIED_DATE IS NOT NULL AND FULLY_APPLIED_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN FULLY_APPLIED_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN FULLY_APPLIED_DATE_TEMP TO FULLY_APPLIED_DATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_ADDRESS ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_ADDRESS
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_ADDRESS DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_ADDRESS RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_ACCT_ADDRESS RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;


-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_ADDRESS ADD COLUMN BIRTHDATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_ADDRESS
SET BIRTHDATE_TEMP = DATE(BIRTHDATE)
WHERE BIRTHDATE IS NOT NULL AND BIRTHDATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_ADDRESS DROP COLUMN BIRTHDATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_ADDRESS RENAME COLUMN BIRTHDATE_TEMP TO BIRTHDATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL_DETAIL
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL_DETAIL DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL ADD COLUMN END_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL_DETAIL
SET END_DATE_TEMP = DATE(END_DATE)
WHERE END_DATE IS NOT NULL AND END_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL_DETAIL DROP COLUMN END_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN END_DATE_TEMP TO END_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL ADD COLUMN UPDATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL_DETAIL
SET UPDATE_DATE_TEMP = DATE(UPDATE_DATE)
WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL_DETAIL DROP COLUMN UPDATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN UPDATE_DATE_TEMP TO UPDATE_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL ADD COLUMN START_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL_DETAIL
SET START_DATE_TEMP = DATE(START_DATE)
WHERE START_DATE IS NOT NULL AND START_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL_DETAIL DROP COLUMN START_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN START_DATE_TEMP TO START_DATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN DH_LOAD_FILE_TEMP VARCHAR,
				DH_LOAD_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET DH_LOAD_FILE_TEMP = DH_LOAD_FILE,
DH_LOAD_DATE_TEMP= DH_LOAD_DATE
;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN DH_LOAD_FILE ,DH_LOAD_DATE ;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_FILE_TEMP TO DH_LOAD_FILE;
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DH_LOAD_DATE_TEMP TO DH_LOAD_DATE;



-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN CREATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET CREATE_DATE_TEMP = DATE(CREATE_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN CREATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN CREATE_DATE_TEMP TO CREATE_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN UPDATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET UPDATE_DATE_TEMP = DATE(UPDATE_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN UPDATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN UPDATE_DATE_TEMP TO UPDATE_DATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN NOTIFY_DATE_TEMP TIMESTAMP;

SELECT   NOTIFY_DATE, TYPEOF(NOTIFY_DATE)  --CAST( AS TIMESTAMP) --()  --DATE(NOTIFY_DATE) 
FROM SRC_ARIA_GL WHERE NOTIFY_DATE IS NOT NULL ;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET NOTIFY_DATE_TEMP = DATE(NOTIFY_DATE)
WHERE NOTIFY_DATE IS NOT NULL AND NOTIFY_DATE != '';      ----------------------XXXXXXXXXXXXXXXXXXX



-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN NOTIFY_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN NOTIFY_DATE_TEMP TO NOTIFY_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN FROM_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET FROM_DATE_TEMP = DATE(FROM_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN FROM_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN FROM_DATE_TEMP TO FROM_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN USAGE_FROM_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET USAGE_FROM_DATE_TEMP = DATE(USAGE_FROM_DATE)
WHERE USAGE_FROM_DATE IS NOT NULL AND USAGE_FROM_DATE != '';
;     ---------------------------XXXXXXXXXXXXXXX



-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN USAGE_FROM_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN USAGE_FROM_DATE_TEMP TO USAGE_FROM_DATE;
---------------------

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN TO_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET TO_DATE_TEMP = DATE(TO_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN TO_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN TO_DATE_TEMP TO TO_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN BILL_TRHU_DATE_TEMP TIMESTAMP;


DESCRIBE TABLE SRC_ARIA_GL;
-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET BILL_TRHU_DATE_TEMP = DATE(BILL_THRU_DATE)
WHERE BILL_THRU_DATE IS NOT NULL AND BILL_THRU_DATE != '';             -------XXXXXXXXXXXX

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN BILL_THRU_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN BILL_TRHU_DATE_TEMP TO BILL_THRU_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN BILL_FROM_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET BILL_FROM_DATE_TEMP = DATE(BILL_FROM_DATE)
WHERE BILL_FROM_DATE IS NOT NULL AND BILL_FROM_DATE != '';                 --------XXXXXXXXXXXXXXXXXXX

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN BILL_FROM_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN BILL_FROM_DATE_TEMP TO BILL_FROM_DATE;
---------------------
SELECT USAGE_TO_DATE_TEMP, USAGE_TO_DATE FROM SRC_ARIA_GL;

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN USAGE_TO_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET USAGE_TO_DATE_TEMP = DATE(USAGE_TO_DATE)
WHERE usage_to_date IS NOT NULL AND usage_to_date != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN USAGE_TO_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN USAGE_TO_DATE_TEMP TO USAGE_TO_DATE;
---------------------
WHERE usage_to_date IS NOT NULL AND usage_to_date != '';

 ------------------------
SELECT * FROM SRC_ARIA_GL;
 -- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN TAX_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET TAX_DATE_TEMP = DATE(TAX_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN TAX_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN TAX_DATE_TEMP TO TAX_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN POSTING_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET POSTING_DATE_TEMP = DATE(POSTING_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN POSTING_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN POSTING_DATE_TEMP TO POSTING_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN DUE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET DUE_DATE_TEMP = DATE(DUE_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN DUE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN DUE_DATE_TEMP TO DUE_DATE;
---------------------
-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL ADD COLUMN BILL_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL
SET BILL_DATE_TEMP = DATE(BILL_DATE);

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL DROP COLUMN BILL_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL RENAME COLUMN BILL_DATE_TEMP TO BILL_DATE;
---------------------

-------------------------------------------------------------------
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ALTER CREATE_DATE SET DATA TYPE TIMESTAMP;


SELECT DATE(due_date) FROM SRC_ARIA_GL; 

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ADD COLUMN CREATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_TRANSACTION
SET CREATE_DATE_TEMP = DATE(CREATE_DATE);

SELECT CREATE_DATE, CREATE_DATE_TEMP FROM SRC_ARIA_ACCT_TRANSACTION;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN CREATE_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN CREATE_DATE_TEMP TO CREATE_DATE;
-- Crear una nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ADD COLUMN UPDATE_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_TRANSACTION
SET UPDATE_DATE_TEMP = DATE(UPDATE_DATE);


DESCRIBE TABLE SRC_ARIA_ACCT_TRANSACTION;
SELECT UPDATE_DATE, CREATE_DATE, RECORDED_DATE FROM SRC_ARIA_ACCT_TRANSACTION;

-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION ADD COLUMN RECORDED_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_ACCT_TRANSACTION
SET RECORDED_DATE_TEMP = DATE(RECORDED_DATE);

SELECT RECORDED_DATE, RECORDED_DATE_TEMP FROM SRC_ARIA_ACCT_TRANSACTION;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN RECORDED_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN RECORDED_DATE_TEMP TO RECORDED_DATE;


-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN RECORDED_DATE_TEMP;

-- Verificar que los datos se migraron correctamente
SELECT UPDATE_DATE, UPDATE_DATE_TEMP
FROM SRC_ARIA_ACCT_TRANSACTION
WHERE UPDATE_DATE_TEMP IS NULL;


SELECT * FROM SRC_ARIA_PLAN_INSTANCE;

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION DROP COLUMN UPDATE_DATE_TEMP;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_ACCT_TRANSACTION RENAME COLUMN UPDATE_DATE_TEMP TO UPDATE_DATE;



*/
