
-------------------------------------------

SELECT * FROM DB_WORKDAY.SH_STAGING.VW_UTIL_CHECK_DUPLICATES;



-------------------------------------------

CREATE OR REPLACE TEMP TABLE  duplicados as
    SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID, HIRE_DATE ORDER BY CONTRACT_START_DATE DESC) AS RN
    FROM DB_WORKDAY.SH_STAGING.WD_HCM
    ) WHERE rn > 1;

DELETE FROM DB_WORKDAY.SH_STAGING.WD_HCM T
        USING duplicados S
        WHERE   T.EMPLOYEE_ID = S.EMPLOYEE_ID
        AND     T.HIRE_DATE = S.HIRE_DATE
;
INSERT INTO DB_WORKDAY.SH_STAGING.WD_HCM
        SELECT * EXCLUDE RN FROM duplicados;
    
------------------------------------------------------

CREATE OR REPLACE TEMP TABLE  duplicados as
    SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY JOB_APPLICATION_REFERENCE_ID ORDER BY LAST_FUNCTIONALLY_UPDATED DESC) AS RN
    FROM DB_WORKDAY.SH_STAGING.WD_CANDIDATES
    ) WHERE rn > 1;

DELETE FROM DB_WORKDAY.SH_STAGING.WD_CANDIDATES T
        USING duplicados S
        WHERE   T.JOB_APPLICATION_REFERENCE_ID = S.JOB_APPLICATION_REFERENCE_ID
        ;

INSERT INTO DB_WORKDAY.SH_STAGING.WD_CANDIDATES
        SELECT * EXCLUDE RN FROM duplicados;
    

------------------------------------------------------


CREATE OR REPLACE TEMP TABLE  duplicados as
    SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY  EMPLOYEE_ID, TIMEOFF_ID, UNITS, TIMEOFF_START_DATE, TIMEOFF, REQUEST_OR_CORRECTION, CREATIONDATE ORDER BY CREATIONDATE DESC) AS RN
    FROM DB_WORKDAY.SH_STAGING.WD_TIME_OFF
    ) WHERE rn > 1;

DELETE FROM DB_WORKDAY.SH_STAGING.WD_TIME_OFF T
        USING duplicados S
        WHERE   T.EMPLOYEE_ID = S.EMPLOYEE_ID AND 
         T.TIMEOFF_ID = S.TIMEOFF_ID AND
         T.UNITS = S.UNITS AND
         T.TIMEOFF_START_DATE = S.TIMEOFF_START_DATE AND
         T.TIMEOFF = S.TIMEOFF AND
         T.REQUEST_OR_CORRECTION = S.REQUEST_OR_CORRECTION AND
         T.CREATIONDATE = S.CREATIONDATE ;
    
INSERT INTO DB_WORKDAY.SH_STAGING.WD_TIME_OFF
        SELECT * EXCLUDE RN FROM duplicados;
    
------------------------------------------------------

CREATE OR REPLACE TEMP TABLE  duplicados as
    SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY  CANDIDATE_EMAIL_ID, EVENT_ID ORDER BY EVENT_ID DESC) AS RN
    FROM DB_WORKDAY.SH_STAGING.PHENOM_EVENTS
    ) WHERE rn > 1;

DELETE FROM DB_WORKDAY.SH_STAGING.PHENOM_EVENTS T
        USING duplicados S
        WHERE  
         T.CANDIDATE_EMAIL_ID = S.CANDIDATE_EMAIL_ID AND
         T.EVENT_ID = S.EVENT_ID  ;
  
INSERT INTO DB_WORKDAY.SH_STAGING.PHENOM_EVENTS
        SELECT * EXCLUDE RN FROM duplicados;

------------------------------------------------------

CREATE OR REPLACE TEMP TABLE  duplicados as
    SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY  IDSURVEYSENT ORDER BY IDSURVEYSENT DESC) AS RN
    FROM DB_WORKDAY.SH_STAGING.SM_SURVEYSENT
    ) WHERE rn > 1;

DELETE FROM DB_WORKDAY.SH_STAGING.SM_SURVEYSENT T
        USING duplicados S
        WHERE  
         T.IDSURVEYSENT = S.IDSURVEYSENT  ;

INSERT INTO DB_WORKDAY.SH_STAGING.SM_SURVEYSENT
        SELECT * EXCLUDE RN FROM duplicados;

