-- Crear nueva columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL ADD COLUMN START_DATE_TEMP TIMESTAMP;

-- Migrar datos desde la columna VARIANT a la nueva columna TIMESTAMP
UPDATE SRC_ARIA_GL_DETAIL
SET START_DATE_TEMP = DATE(START_DATE)
WHERE START_DATE IS NOT NULL AND START_DATE != '';

-- Eliminar la columna original
ALTER TABLE SRC_ARIA_GL_DETAIL DROP COLUMN START_DATE;

-- Renombrar la columna temporal
ALTER TABLE SRC_ARIA_GL_DETAIL RENAME COLUMN START_DATE_TEMP TO START_DATE;
---------------------
