ALTER TABLE DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
ADD COLUMN POSTAL_CODE_OTHER_KILLER_QUESTIONS_NEW VARCHAR(1000);

UPDATE DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
SET POSTAL_CODE_OTHER_KILLER_QUESTIONS_NEW = LEFT(POSTAL_CODE_OTHER_KILLER_QUESTIONS,1000);

ALTER TABLE DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
DROP COLUMN POSTAL_CODE_OTHER_KILLER_QUESTIONS ;

ALTER TABLE DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
RENAME COLUMN POSTAL_CODE_OTHER_KILLER_QUESTIONS_NEW TO  POSTAL_CODE_OTHER_KILLER_QUESTIONS;
