CALL DB_METADATA.SH_MAIN.SP_CREATE_LOAD_PROCESS (
    P_ID_PROCESS_TYPE => 4,
    P_ID_PROCESS_GROUP => 25,
    --P_ID_SOURCE_DATA_STORE => 2322,
    --P_ID_TARGET_DATA_STORE => 2323,
    P_ID_COUNTRY => 2,
    P_DS_LOAD_PROCESS_NAME => 'SP_EXEC_ODS_REC_FACT_TARIFICADOR_VOLTE',
    P_DS_RECORD_STATUS => 'ACTIVE',
    P_IN_EXECUTION_ORDER  => 1, 
    P_IN_EXECUTION  => 1,
    P_DS_QUERY => 'CALL DB_ODIN.SH_MAIN.SP_ODS_REC_FACT_TARIFICADOR_VOLTE();', 
    P_IN_DEPENDENCE  => 1
);



USE DATABASE DB_ODIN;
USE SCHEMA SH_STAGING;
CREATE OR REPLACE TASK TASK_EXEC_SP_ODS_REC_FACT_TARIFICADOR_VOLTE
  WAREHOUSE = 'COMPUTE_WH'
  AFTER TASK_EXEC_SP_COPY_TABLE_JSON_SRC_CU_TRACES
AS  
  CALL DB_METADATA.SH_MAIN.SP_EXECUTE_SP_METADATA('SP_EXEC_ODS_REC_FACT_TARIFICADOR_VOLTE');

ALTER TASK TASK_EXEC_SP_ODS_REC_FACT_TARIFICADOR_VOLTE RESUME;
