CREATE OR REPLACE PROCEDURE DB_ODS_BILLING.SH_STAGING.SP_COPY_TABLE_PARQUET_INIT_END("P_DS_LOAD_PROCESS_NAME" VARCHAR(250), "P_STAGE_SOURCE" VARCHAR(250), "P_DATABASE" VARCHAR(250), "P_SCHEMA" VARCHAR(250), "P_TABLE_TARGET" VARCHAR(250), "P_PATTERN" VARCHAR(250) DEFAULT '', "P_ON_ERROR" VARCHAR(250) DEFAULT 'CONTINUE', "P_EXTRA_COLUMN" VARCHAR(250) DEFAULT null, "P_EXTRA_COLUMN_VALUE" VARCHAR(250) DEFAULT null, "P_COMPRESSION" VARCHAR(250) DEFAULT 'AUTO', "P_INCLUDE_METADATA" NUMBER(38,0) DEFAULT 1)
RETURNS VARCHAR(50)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_SQL_QUERY VARCHAR(5000);
    V_COMPRESSION VARCHAR(100);
    V_SQL_RESPONSE VARCHAR(5000);
    V_AUX string;
    V_PROCESS_ID string;
    V_PROCESS_ID_LOG string;
    V_ERROR INTEGER;
    V_ERROR_MSG string;
BEGIN
    V_ERROR := 0;
    V_SQL_QUERY := '''';
    V_PROCESS_ID := (SELECT ID_LOAD_PROCESS FROM DB_METADATA.SH_MAIN.D_DWH_LOAD_PROCESS WHERE DS_LOAD_PROCESS_NAME = :P_DS_LOAD_PROCESS_NAME);
    V_PROCESS_ID_LOG := (CALL DB_METADATA.SH_MAIN.SP_INIT_METADATA_LOG (:P_DS_LOAD_PROCESS_NAME));

    IF (P_DATABASE IS NULL OR P_DATABASE = '''') THEN
        V_ERROR := 2;
    ELSE
        V_SQL_QUERY := ''COPY INTO '' || P_DATABASE || V_SQL_QUERY;
    END IF;

    IF (P_SCHEMA IS NULL OR P_SCHEMA = '''') THEN
        V_ERROR := 3;
    ELSE
        V_SQL_QUERY := V_SQL_QUERY || ''.'' || P_SCHEMA;
    END IF;

    IF (P_TABLE_TARGET IS NULL OR P_TABLE_TARGET = '''') THEN
        V_ERROR := 4;
    ELSE
        V_SQL_QUERY := V_SQL_QUERY || ''.'' || P_TABLE_TARGET;
    END IF;

    IF (P_STAGE_SOURCE IS NULL OR P_STAGE_SOURCE = '''') THEN
        V_ERROR := 5;
    ELSE
        V_SQL_QUERY := V_SQL_QUERY || '' FROM @'' || P_STAGE_SOURCE || '''' ;
    END IF;

    V_SQL_QUERY := V_SQL_QUERY || '' FILE_FORMAT = ( TYPE = PARQUET '';
    V_SQL_QUERY := V_SQL_QUERY || ''COMPRESSION = '' || P_COMPRESSION || '') '';
    V_SQL_QUERY := V_SQL_QUERY || ''MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE '';

    IF (P_INCLUDE_METADATA = 1) THEN
        V_SQL_QUERY := V_SQL_QUERY || '' INCLUDE_METADATA = (DH_LOAD_FILE = METADATA$FILENAME,
                                DH_LOAD_DATE = METADATA$START_SCAN_TIME) '';
    END IF;

    IF (P_PATTERN IS NOT NULL AND P_PATTERN <> '''') THEN
        V_SQL_QUERY := V_SQL_QUERY || '' PATTERN = '''''' || P_PATTERN || '''''''';
    END IF;

    IF (P_ON_ERROR IS NOT NULL AND P_ON_ERROR <> '''') THEN
        V_SQL_QUERY := V_SQL_QUERY || '' ON_ERROR = '''''' || P_ON_ERROR || '''''''';
    END IF;


    
    BEGIN
        EXECUTE IMMEDIATE :V_SQL_QUERY;
    EXCEPTION
      WHEN statement_error OR expression_error THEN
        V_ERROR_MSG := :SQLSTATE || '' - '' || :sqlerrm;
        V_ERROR := 1;
      WHEN OTHER THEN
        V_ERROR_MSG := :SQLSTATE || '' - '' || :sqlerrm;
        V_ERROR := 0;
    END;

    IF (P_EXTRA_COLUMN IS NOT NULL AND P_EXTRA_COLUMN <> '''') THEN
   
        V_AUX :=   ''UPDATE '' || P_DATABASE || ''.'' ||  P_SCHEMA  || ''.'' ||  P_TABLE_TARGET || '' SET '' || P_EXTRA_COLUMN  || ''= '''''' ||  P_EXTRA_COLUMN_VALUE  || '''''''' || '' WHERE '' || P_EXTRA_COLUMN  || '' IS NULL AND TO_DATE(DH_LOAD_DATE) = CURRENT_DATE'' ;
        EXECUTE IMMEDIATE :V_AUX;
    
    END IF;   
/*
    IF (V_ERROR = 0) THEN
        CALL DB_METADATA.SH_MAIN.SP_FINISH_METADATA_LOG (:P_DS_LOAD_PROCESS_NAME, :V_PROCESS_ID_LOG, :V_SQL_RESPONSE, ''SUCCESS'', '''', ''PROCEDURE EXECUTION'');
    ELSE
        CALL DB_METADATA.SH_MAIN.SP_FINISH_METADATA_LOG (:P_DS_LOAD_PROCESS_NAME, :V_PROCESS_ID_LOG, :V_SQL_RESPONSE, ''ERROR''  , '''', ''PROCEDURE EXECUTION'');
    END IF;
*/
    RETURN :V_PROCESS_ID_LOG;
    
END';

