USE SCHEMA DB_ODIN.SH_STAGING;

// Create procedure

CREATE OR REPLACE PROCEDURE DB_ODIN.SH_STAGING.SP_COPY_TABLE_JSON (P_DATABASE VARCHAR, P_SCHEMA VARCHAR, P_TABLE_TARGET VARCHAR, P_TABLE_SOURCE VARCHAR, P_PATTERN VARCHAR, P_COMPRESSION VARCHAR, P_TRUNCATECOLUMNS BOOLEAN DEFAULT FALSE)
returns INTEGER NOT NULL
language SQL

AS

declare

    V_SQL_QUERY VARCHAR(5000);
    V_COMPRESSION VARCHAR(100);
    V_SQL_RESPONSE VARCHAR(5000);
    V_AUX string;
begin


    V_COMPRESSION := :P_COMPRESSION;
    V_COMPRESSION := IFNULL(V_COMPRESSION,'AUTO');
    V_SQL_QUERY := 'COPY INTO ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE_TARGET || '
                   FROM ' || P_TABLE_SOURCE || ' MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ' || ' TRUNCATECOLUMNS = ' || P_TRUNCATECOLUMNS || '
                   FILE_FORMAT = ( TYPE = JSON COMPRESSION = ' || V_COMPRESSION || ')
                   pattern=' || '"' || P_PATTERN || '"';


    EXECUTE IMMEDIATE :V_SQL_QUERY;

    V_AUX := (SELECT TOP 1 $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

    if (V_AUX='Copy executed with 0 files processed.')
    then
        V_SQL_RESPONSE := '0';
    ELSE
        V_SQL_RESPONSE := (SELECT SUM($4) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID(-2))));

    END IF;


    RETURN V_SQL_RESPONSE;

END;