CREATE OR REPLACE PROCEDURE DB_WORKDAY.SH_MAIN.SP_DIM_CANDIDATE()
RETURNS VARCHAR(250)
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    VAR_TODATE TIMESTAMPLTZ;
    VAR_EXECUTION INT;
    VAR_ACTIVE INT;
    VAR_INSERTED INT;
    VAR_DELETED INT;
    VAR_UPDATED INT;
    VAR_DS_MESSAGE VARCHAR;

BEGIN

    -- Define current time 
    
    SET VAR_TODATE := CURRENT_TIMESTAMP(2);

    -- Check Active flag on CONTROL_FLOW_INFO



        -- Log Execution in CONTROL_LOAD_INFO with status 'Started'
        
        INSERT INTO DB_WORKDAY.SH_MAIN.AUX_CONTROL_LOAD_INFO  (
            DS_TARGET_TABLE_NAME, DS_SOURCE_TABLE_NAME, DS_SOURCE_OBJECT_SCHEMA, DS_STATUS)
        VALUES ( 'DIM_CANDIDATE', 'DB_WORKDAY.SH_STAGING.VW_DIM_CANDIDATE', 'DIM', 'STARTED')
        ;

        -- Get last Execution ID
        
        SELECT MAX(ID)
        INTO :VAR_EXECUTION
        FROM DB_WORKDAY.SH_MAIN.AUX_CONTROL_LOAD_INFO
        WHERE DS_TARGET_TABLE_NAME = 'DIM_CANDIDATE'
          AND DS_STATUS = 'STARTED';

        -- Empty CHANGE table
        
        TRUNCATE TABLE DB_WORKDAY.SH_MAIN.AUX_CANDIDATE_CHANGES;

        -- Insert new or updated records on Change Table
            INSERT INTO DB_WORKDAY.SH_MAIN.AUX_CANDIDATE_CHANGES (
                IDCANDIDATES,
                IDCANDIDATE,
                CANDIDATEFULLNAME,
                CANDIDATEAGE,
                CANDIDATEEMAIL,
                CANDIDATEPHONE,
                CANDIDATECITY,
                CANDIDATETAGS,
                CANDIDATEPOOLS,
                FROMDATE,
                COUNTRY,
                SQ_ROW_HASH_T1,
                SQ_EXECUTION_ID,
                SQ_EXECUTION_ID_INSERTED,
                SQ_OPERATION_ID, 
                GENDER,
                ISPURGED,
                CURRENT_COMPANY,
                SKILL,
                HIRING_STATUS,
                PREFERRED_CATEGORY,
                PREFERRED_LOCATION,
                NOTES,
                "INTERNAL_EXTERNAL",
                LEAD_SOURCE,
                LANGUAGE,
                "DEGREE_CERTIFICATE",
                "MAJOR_FIELD_OF_STUDY",
                UNIVERSITY,
                CURRENT_OR_PAST_COMPANIES,
                CURRENT_OR_PAST_JOB_TITLES,
                CURRENT_OR_PAST_JOB_LOCATIONS,
                UTM_MEDIUM,
                UTM_CAMPAIGN,
                ZIPCODE,
                HIGHEST_EDUCATION,
                EDUCATION_START_DATE,
                EDUCATION_END_DATE,
                CANDIDATE_PREFERRED_LOCATION,
                AVAILABILITY_TO_START,
                SALARY_EXPECTATIONS,
                CURRENT_SALARY,
                YEARS_OF_EXPERIENCE,
                LOCAL_LANGUAGE_LEVEL,
                "CONTRACTOR_PROFILE_RECRUITERFILLS",
                CUSTOMER_SERVICE_EXPERIENCE,
                CURRENT_BENEFITS,
                CLEAN_CRIMINAL_RECORD,
                EXPERIENCE_IN_THE_AREA,
                PREFERRED_SHIFT,
                OWN_VEHICLE,
                FLEXIBLE_HOURS,
                CURRENTLY_EMPLOYED,
                SALES_EXPERIENCE,
                DRIVERS_LICENSE,
                MOTIVATION,
                PREFERRED_WORK_SCHEDULE,
                POSTAL_CODE,
                DRIVING_LICENSE,
                YEARS_SALES_EXPERIENCE,
                "CAR_RECRUITERFILLS",
                SALES_EXPERIENCE_TYPE,
                SHIFT_AVAILABILITY_HOURS,
                ENGLISH_LEVEL,
                TEAM_MANAGEMENT_EXPERIENCE,
                SELF_PROFILE_CONSIDERATION,
                MOBILITY,
                WORK_PERMIT,
                "INFORMATIONAL_GROUPING_NORDICS",
                "INFORMATIONAL_GROUPING_PERU",
                "INFORMATIONAL_GROUPING_PERU_KILL",
                "INFORMATIONAL_GROUPING_ARGENTINA",
                ASSESSMENT,
                ASSESSMENT_TOTAL_SCORE,
                SHIFT_AVAILABILITY_DAYS,
                MEET_LEGAL_AGE_REQUIREMENT,
                COLD_CANVASSING,
                HOW_DID_YOU_HEAR_ABOUT_US,
                LAST_EMAIL_RESPONSE,
                LAST_EMAIL_SENT,
                PRIMARY_NATIONALITY,
                TIMES_CALLED_CANDIDATE,
                REFERRER,
                "COLD_CANVASSING_RECRUITER_FILLS",
                EDUCATION_LEVEL,
                WORK_PERMIT_RECRUITER_FILLS,
                MOBILITY_RECRUITER_FILLS,
                CODE_POSTAL_CANDIDATE,
                TITULAIRE_DU_PERMIS_B,
                PERSON_VEHICLE,
                CLEAN_RECORD,
                WHEN_ARE_YOU_AVAILABLE,
                AVAILABLE_EVENINGANDSATURDAYS,
                OK_PRINCIPLE_COMMISSION_REMUNERATION,
                EVALUATION_GLOBALE,
                CANDIDAT_ACTUELLEMENT_EN_POSTE,
                DO_YOU_MEET_THE_LEGAL_AGE,
                DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
                ARE_YOU_CURRENTLY_EMPLOYED,
                ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
                WHAT_IS_YOUR_POSTAL_CODE,
                ARE_YOU_OK_WITH_WORK_TIMINGS,
                CANDIDATE_SCORE,
                SALES_OR_CUSTOMER_FACING_EXPERIENCE,
                DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
                OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
                SCHEDULE_START_DATE,
                EMAILPRIMARYHOME,
                EMAILPRIMARYWORK,
                REFERRALDATE,
                INTERNAL,
                TAGS_PHENOM,
                POSTAL_CODE_OTHER_KILLER_QUESTIONS,
                WHAT_IS_THE_CANDIDATE_GENDER,
                WHAT_IS_THE_WORK_PERMIT_TYPE,
                YEAR_OF_EXPERIENCE_ROLE,
                BONUS,
                TOOLS,
                ES_MOTIVATION,
                ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
                DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE
            ) WITH CTE_CHANGE_WITH_HASH AS (
                SELECT
                    /* Hash update type 1 */
                    HASH(
                        CANDIDATEAGE,
                        CANDIDATECITY,
                        CANDIDATEEMAIL,
                        CANDIDATEFULLNAME,
                        CANDIDATEPHONE,
                        CANDIDATEPOOLS,
                        CANDIDATETAGS,
                        COUNTRY,
                        GENDER,
                        IDCANDIDATE,
                        ISPURGED,
                        CURRENT_COMPANY,
                        SKILL,
                        HIRING_STATUS,
                        PREFERRED_CATEGORY,
                        PREFERRED_LOCATION,
                        NOTES,
                        "INTERNAL_EXTERNAL",
                        LEAD_SOURCE,
                        LANGUAGE,
                        "DEGREE_CERTIFICATE",
                        "MAJOR_FIELD_OF_STUDY",
                        UNIVERSITY,
                        CURRENT_OR_PAST_COMPANIES,
                        CURRENT_OR_PAST_JOB_TITLES,
                        CURRENT_OR_PAST_JOB_LOCATIONS,
                        UTM_MEDIUM,
                        UTM_CAMPAIGN,
                        ZIPCODE,
                        HIGHEST_EDUCATION,
                        EDUCATION_START_DATE,
                        EDUCATION_END_DATE,
                        CANDIDATE_PREFERRED_LOCATION,
                        AVAILABILITY_TO_START,
                        SALARY_EXPECTATIONS,
                        CURRENT_SALARY,
                        YEARS_OF_EXPERIENCE,
                        LOCAL_LANGUAGE_LEVEL,
                        "CONTRACTOR_PROFILE_RECRUITERFILLS",
                        CUSTOMER_SERVICE_EXPERIENCE,
                        CURRENT_BENEFITS,
                        CLEAN_CRIMINAL_RECORD,
                        EXPERIENCE_IN_THE_AREA,
                        PREFERRED_SHIFT,
                        OWN_VEHICLE,
                        FLEXIBLE_HOURS,
                        CURRENTLY_EMPLOYED,
                        SALES_EXPERIENCE,
                        DRIVERS_LICENSE,
                        MOTIVATION,
                        PREFERRED_WORK_SCHEDULE,
                        POSTAL_CODE,
                        DRIVING_LICENSE,
                        YEARS_SALES_EXPERIENCE,
                        "CAR_RECRUITERFILLS",
                        SALES_EXPERIENCE_TYPE,
                        SHIFT_AVAILABILITY_HOURS,
                        ENGLISH_LEVEL,
                        TEAM_MANAGEMENT_EXPERIENCE,
                        SELF_PROFILE_CONSIDERATION,
                        MOBILITY,
                        WORK_PERMIT,
                        "INFORMATIONAL_GROUPING_NORDICS",
                        "INFORMATIONAL_GROUPING_PERU",
                        "INFORMATIONAL_GROUPING_PERU_KILL",
                        "INFORMATIONAL_GROUPING_ARGENTINA",
                        ASSESSMENT,
                        ASSESSMENT_TOTAL_SCORE,
                        SHIFT_AVAILABILITY_DAYS,
                        MEET_LEGAL_AGE_REQUIREMENT,
                        COLD_CANVASSING,
                        HOW_DID_YOU_HEAR_ABOUT_US,
                        LAST_EMAIL_RESPONSE,
                        LAST_EMAIL_SENT,
                        PRIMARY_NATIONALITY,
                        TIMES_CALLED_CANDIDATE,
                        REFERRER,
                        "COLD_CANVASSING_RECRUITER_FILLS",
                        EDUCATION_LEVEL,
                        WORK_PERMIT_RECRUITER_FILLS,
                        MOBILITY_RECRUITER_FILLS,
                        CODE_POSTAL_CANDIDATE,
                        TITULAIRE_DU_PERMIS_B,
                        PERSON_VEHICLE,
                        CLEAN_RECORD,
                        WHEN_ARE_YOU_AVAILABLE,
                        AVAILABLE_EVENINGANDSATURDAYS,
                        OK_PRINCIPLE_COMMISSION_REMUNERATION,
                        EVALUATION_GLOBALE,
                        EMAILPRIMARYHOME,
                        EMAILPRIMARYWORK,
                        REFERRALDATE,
                        CANDIDAT_ACTUELLEMENT_EN_POSTE,
                        DO_YOU_MEET_THE_LEGAL_AGE,
                        DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
                        ARE_YOU_CURRENTLY_EMPLOYED,
                        ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
                        WHAT_IS_YOUR_POSTAL_CODE,
                        ARE_YOU_OK_WITH_WORK_TIMINGS,
                        CANDIDATE_SCORE,
                        SALES_OR_CUSTOMER_FACING_EXPERIENCE,
                        DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
                        OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
                        SCHEDULE_START_DATE,
                        INTERNAL,
                        TAGS_PHENOM,
                        POSTAL_CODE_OTHER_KILLER_QUESTIONS,
                        WHAT_IS_THE_CANDIDATE_GENDER,
                        WHAT_IS_THE_WORK_PERMIT_TYPE,
                        YEAR_OF_EXPERIENCE_ROLE,
                        BONUS,
                        TOOLS,
                        ES_MOTIVATION,
                        ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
                        DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE
                    ) AS SQ_ROW_HASH_T1,
                    *
                FROM DB_WORKDAY.SH_STAGING.VW_DIM_CANDIDATE
            ),
            CTE_CHANGE_WITH_OPERATION AS (
                SELECT DISTINCT CHANGE.*  EXCLUDE SQ_EXECUTION_ID,
                    CASE
                        -- iNSERT New records
                        WHEN (DIM.IDCANDIDATES IS NULL) THEN 1 
                        -- Update type 1: Update changes
                        WHEN CHANGE.SQ_ROW_HASH_T1 <> DIM.SQ_ROW_HASH_T1 THEN 2 
                        -- Update type 2: version record 
                    --     WHEN CHANGE.SQ_ROW_HASH_T2 <> DIM.SQ_ROW_HASH_T2 THEN 3
                        ELSE 0
                    END AS SQ_OPERATION_ID,
                    NVL(DIM.SQ_EXECUTION_ID, :VAR_EXECUTION) AS SQ_EXECUTION_ID, 
                    NVL(DIM.SQ_EXECUTION_ID_INSERTED, :VAR_EXECUTION) AS SQ_EXECUTION_ID_INSERTED, -- IF EXISTS KEEP THE FIRST INSERTION ID, IF NOT SET CURRENT EXECUTION
                FROM CTE_CHANGE_WITH_HASH CHANGE
                    LEFT JOIN DB_WORKDAY.SH_MAIN.DIM_CANDIDATE DIM ON CHANGE.IDCANDIDATES = DIM.IDCANDIDATES
            )
            SELECT IDCANDIDATES,
                IDCANDIDATE,
                CANDIDATEFULLNAME,
                CANDIDATEAGE,
                CANDIDATEEMAIL,
                CANDIDATEPHONE,
                CANDIDATECITY,
                CANDIDATETAGS,
                CANDIDATEPOOLS,
                :VAR_TODATE AS FROMDATE,
                COUNTRY,
                SQ_ROW_HASH_T1,
                SQ_EXECUTION_ID,
                SQ_EXECUTION_ID_INSERTED,
                SQ_OPERATION_ID, 
                GENDER,
                ISPURGED,
                CURRENT_COMPANY,
                SKILL,
                HIRING_STATUS,
                PREFERRED_CATEGORY,
                PREFERRED_LOCATION,
                NOTES,
                "INTERNAL_EXTERNAL",
                LEAD_SOURCE,
                "LANGUAGE",
                "DEGREE_CERTIFICATE",
                "MAJOR_FIELD_OF_STUDY",
                UNIVERSITY,
                CURRENT_OR_PAST_COMPANIES,
                CURRENT_OR_PAST_JOB_TITLES,
                CURRENT_OR_PAST_JOB_LOCATIONS,
                UTM_MEDIUM,
                UTM_CAMPAIGN,
                ZIPCODE,
                HIGHEST_EDUCATION,
                EDUCATION_START_DATE,
                EDUCATION_END_DATE,
                CANDIDATE_PREFERRED_LOCATION,
                AVAILABILITY_TO_START,
                SALARY_EXPECTATIONS,
                CURRENT_SALARY,
                YEARS_OF_EXPERIENCE,
                LOCAL_LANGUAGE_LEVEL,
                "CONTRACTOR_PROFILE_RECRUITERFILLS",
                CUSTOMER_SERVICE_EXPERIENCE,
                CURRENT_BENEFITS,
                CLEAN_CRIMINAL_RECORD,
                EXPERIENCE_IN_THE_AREA,
                PREFERRED_SHIFT,
                OWN_VEHICLE,
                FLEXIBLE_HOURS,
                CURRENTLY_EMPLOYED,
                SALES_EXPERIENCE,
                DRIVERS_LICENSE,
                MOTIVATION,
                PREFERRED_WORK_SCHEDULE,
                POSTAL_CODE,
                DRIVING_LICENSE,
                YEARS_SALES_EXPERIENCE,
                "CAR_RECRUITERFILLS",
                SALES_EXPERIENCE_TYPE,
                SHIFT_AVAILABILITY_HOURS,
                ENGLISH_LEVEL,
                TEAM_MANAGEMENT_EXPERIENCE,
                SELF_PROFILE_CONSIDERATION,
                MOBILITY,
                WORK_PERMIT,
                "INFORMATIONAL_GROUPING_NORDICS",
                "INFORMATIONAL_GROUPING_PERU",
                "INFORMATIONAL_GROUPING_PERU_KILL",
                "INFORMATIONAL_GROUPING_ARGENTINA",
                ASSESSMENT,
                ASSESSMENT_TOTAL_SCORE,
                SHIFT_AVAILABILITY_DAYS,
                MEET_LEGAL_AGE_REQUIREMENT,
                COLD_CANVASSING,
                HOW_DID_YOU_HEAR_ABOUT_US,
                LAST_EMAIL_RESPONSE,
                LAST_EMAIL_SENT,
                PRIMARY_NATIONALITY,
                TIMES_CALLED_CANDIDATE,
                REFERRER,
                "COLD_CANVASSING_RECRUITER_FILLS",
                EDUCATION_LEVEL,
                WORK_PERMIT_RECRUITER_FILLS,
                MOBILITY_RECRUITER_FILLS,
                CODE_POSTAL_CANDIDATE,
                TITULAIRE_DU_PERMIS_B,
                PERSON_VEHICLE,
                CLEAN_RECORD,
                WHEN_ARE_YOU_AVAILABLE,
                AVAILABLE_EVENINGANDSATURDAYS,
                OK_PRINCIPLE_COMMISSION_REMUNERATION,
                EVALUATION_GLOBALE,
                CANDIDAT_ACTUELLEMENT_EN_POSTE,
                DO_YOU_MEET_THE_LEGAL_AGE,
                DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
                ARE_YOU_CURRENTLY_EMPLOYED,
                ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
                WHAT_IS_YOUR_POSTAL_CODE,
                ARE_YOU_OK_WITH_WORK_TIMINGS,
                CANDIDATE_SCORE,
                SALES_OR_CUSTOMER_FACING_EXPERIENCE,
                DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
                OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
                SCHEDULE_START_DATE,
                EMAILPRIMARYHOME,
                EMAILPRIMARYWORK,
                REFERRALDATE,
                INTERNAL,
                TAGS_PHENOM,
                POSTAL_CODE_OTHER_KILLER_QUESTIONS,
                WHAT_IS_THE_CANDIDATE_GENDER,
                WHAT_IS_THE_WORK_PERMIT_TYPE,
                YEAR_OF_EXPERIENCE_ROLE,
                BONUS,
                TOOLS,
                ES_MOTIVATION,
                ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
                DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE
            FROM CTE_CHANGE_WITH_OPERATION
            WHERE SQ_OPERATION_ID <> 0; --Skip records with no changes



    -- Update data from change table to end table

        UPDATE DB_WORKDAY.SH_MAIN.DIM_CANDIDATE DIM
            SET
            DIM.SQ_OPERATION_ID = CHANGE.SQ_OPERATION_ID, 
            DIM.CANDIDATEAGE = CHANGE.CANDIDATEAGE,
            DIM.CANDIDATECITY = CHANGE.CANDIDATECITY,
            DIM.CANDIDATEEMAIL = CHANGE.CANDIDATEEMAIL,
            DIM.CANDIDATEFULLNAME = CHANGE.CANDIDATEFULLNAME,
            DIM.CANDIDATEPHONE = CHANGE.CANDIDATEPHONE,
            DIM.CANDIDATEPOOLS = CHANGE.CANDIDATEPOOLS,
            DIM.CANDIDATETAGS = CHANGE.CANDIDATETAGS,
            DIM.COUNTRY = CHANGE.COUNTRY,
            DIM.GENDER = CHANGE.GENDER,
            DIM.IDCANDIDATE = CHANGE.IDCANDIDATE,
            DIM.ISPURGED = CHANGE.ISPURGED,
            DIM.CURRENT_COMPANY = CHANGE.CURRENT_COMPANY,
            DIM.SKILL = CHANGE.SKILL,
            DIM.HIRING_STATUS = CHANGE.HIRING_STATUS,
            DIM.PREFERRED_CATEGORY = CHANGE.PREFERRED_CATEGORY,
            DIM.PREFERRED_LOCATION = CHANGE.PREFERRED_LOCATION,
            DIM.NOTES = CHANGE.NOTES,
            DIM."INTERNAL_EXTERNAL" = CHANGE."INTERNAL_EXTERNAL",
            DIM.LEAD_SOURCE = CHANGE.LEAD_SOURCE,
            DIM."LANGUAGE" = CHANGE."LANGUAGE",
            DIM."DEGREE_CERTIFICATE" = CHANGE."DEGREE_CERTIFICATE",
            DIM."MAJOR_FIELD_OF_STUDY" = CHANGE."MAJOR_FIELD_OF_STUDY",
            DIM.UNIVERSITY = CHANGE.UNIVERSITY,
            DIM.CURRENT_OR_PAST_COMPANIES = CHANGE.CURRENT_OR_PAST_COMPANIES,
            DIM.CURRENT_OR_PAST_JOB_TITLES = CHANGE.CURRENT_OR_PAST_JOB_TITLES,
            DIM.CURRENT_OR_PAST_JOB_LOCATIONS = CHANGE.CURRENT_OR_PAST_JOB_LOCATIONS,
            DIM.UTM_MEDIUM = CHANGE.UTM_MEDIUM,
            DIM.UTM_CAMPAIGN = CHANGE.UTM_CAMPAIGN,
            DIM.ZIPCODE = CHANGE.ZIPCODE,
            DIM.HIGHEST_EDUCATION = CHANGE.HIGHEST_EDUCATION,
            DIM.EDUCATION_START_DATE = CHANGE.EDUCATION_START_DATE,
            DIM.EDUCATION_END_DATE = CHANGE.EDUCATION_END_DATE,
            DIM.CANDIDATE_PREFERRED_LOCATION = CHANGE.CANDIDATE_PREFERRED_LOCATION,
            DIM.AVAILABILITY_TO_START = CHANGE.AVAILABILITY_TO_START,
            DIM.SALARY_EXPECTATIONS = CHANGE.SALARY_EXPECTATIONS,
            DIM.CURRENT_SALARY = CHANGE.CURRENT_SALARY,
            DIM.YEARS_OF_EXPERIENCE = CHANGE.YEARS_OF_EXPERIENCE,
            DIM.LOCAL_LANGUAGE_LEVEL = CHANGE.LOCAL_LANGUAGE_LEVEL,
            DIM."CONTRACTOR_PROFILE_RECRUITERFILLS" = CHANGE."CONTRACTOR_PROFILE_RECRUITERFILLS",
            DIM.CUSTOMER_SERVICE_EXPERIENCE = CHANGE.CUSTOMER_SERVICE_EXPERIENCE,
            DIM.CURRENT_BENEFITS = CHANGE.CURRENT_BENEFITS,
            DIM.CLEAN_CRIMINAL_RECORD = CHANGE.CLEAN_CRIMINAL_RECORD,
            DIM.EXPERIENCE_IN_THE_AREA = CHANGE.EXPERIENCE_IN_THE_AREA,
            DIM.PREFERRED_SHIFT = CHANGE.PREFERRED_SHIFT,
            DIM.OWN_VEHICLE = CHANGE.OWN_VEHICLE,
            DIM.FLEXIBLE_HOURS = CHANGE.FLEXIBLE_HOURS,
            DIM.CURRENTLY_EMPLOYED = CHANGE.CURRENTLY_EMPLOYED,
            DIM.SALES_EXPERIENCE = CHANGE.SALES_EXPERIENCE,
            DIM.DRIVERS_LICENSE = CHANGE.DRIVERS_LICENSE,
            DIM.MOTIVATION = CHANGE.MOTIVATION,
            DIM.PREFERRED_WORK_SCHEDULE = CHANGE.PREFERRED_WORK_SCHEDULE,
            DIM.POSTAL_CODE = CHANGE.POSTAL_CODE,
            DIM.DRIVING_LICENSE = CHANGE.DRIVING_LICENSE,
            DIM.YEARS_SALES_EXPERIENCE = CHANGE.YEARS_SALES_EXPERIENCE,
            DIM."CAR_RECRUITERFILLS" = CHANGE."CAR_RECRUITERFILLS",
            DIM.SALES_EXPERIENCE_TYPE = CHANGE.SALES_EXPERIENCE_TYPE,
            DIM.SHIFT_AVAILABILITY_HOURS = CHANGE.SHIFT_AVAILABILITY_HOURS,
            DIM.ENGLISH_LEVEL = CHANGE.ENGLISH_LEVEL,
            DIM.TEAM_MANAGEMENT_EXPERIENCE = CHANGE.TEAM_MANAGEMENT_EXPERIENCE,
            DIM.SELF_PROFILE_CONSIDERATION = CHANGE.SELF_PROFILE_CONSIDERATION,
            DIM.MOBILITY = CHANGE.MOBILITY,
            DIM.WORK_PERMIT = CHANGE.WORK_PERMIT,
            DIM."INFORMATIONAL_GROUPING_NORDICS" = CHANGE."INFORMATIONAL_GROUPING_NORDICS",
            DIM."INFORMATIONAL_GROUPING_PERU" = CHANGE."INFORMATIONAL_GROUPING_PERU",
            DIM."INFORMATIONAL_GROUPING_PERU_KILL" = CHANGE."INFORMATIONAL_GROUPING_PERU_KILL",
            DIM."INFORMATIONAL_GROUPING_ARGENTINA" = CHANGE."INFORMATIONAL_GROUPING_ARGENTINA",
            DIM.ASSESSMENT = CHANGE.ASSESSMENT,
            DIM.ASSESSMENT_TOTAL_SCORE = CHANGE.ASSESSMENT_TOTAL_SCORE,
            DIM.SHIFT_AVAILABILITY_DAYS = CHANGE.SHIFT_AVAILABILITY_DAYS,
            DIM.MEET_LEGAL_AGE_REQUIREMENT = CHANGE.MEET_LEGAL_AGE_REQUIREMENT,
            DIM.COLD_CANVASSING = CHANGE.COLD_CANVASSING,
            DIM.HOW_DID_YOU_HEAR_ABOUT_US = CHANGE.HOW_DID_YOU_HEAR_ABOUT_US,
            DIM.LAST_EMAIL_RESPONSE = CHANGE.LAST_EMAIL_RESPONSE,
            DIM.LAST_EMAIL_SENT = CHANGE.LAST_EMAIL_SENT,
            DIM.PRIMARY_NATIONALITY = CHANGE.PRIMARY_NATIONALITY,
            DIM.TIMES_CALLED_CANDIDATE = CHANGE.TIMES_CALLED_CANDIDATE,
            DIM.REFERRER = CHANGE.REFERRER,
            DIM."COLD_CANVASSING_RECRUITER_FILLS" = CHANGE."COLD_CANVASSING_RECRUITER_FILLS",
            DIM.EDUCATION_LEVEL = CHANGE.EDUCATION_LEVEL,
            DIM.WORK_PERMIT_RECRUITER_FILLS = CHANGE.WORK_PERMIT_RECRUITER_FILLS,
            DIM.MOBILITY_RECRUITER_FILLS = CHANGE.MOBILITY_RECRUITER_FILLS,
            DIM.CODE_POSTAL_CANDIDATE = CHANGE.CODE_POSTAL_CANDIDATE,
            DIM.TITULAIRE_DU_PERMIS_B = CHANGE.TITULAIRE_DU_PERMIS_B,
            DIM.PERSON_VEHICLE = CHANGE.PERSON_VEHICLE,
            DIM.CLEAN_RECORD = CHANGE.CLEAN_RECORD,
            DIM.WHEN_ARE_YOU_AVAILABLE = CHANGE.WHEN_ARE_YOU_AVAILABLE,
            DIM.AVAILABLE_EVENINGANDSATURDAYS = CHANGE.AVAILABLE_EVENINGANDSATURDAYS,
            DIM.OK_PRINCIPLE_COMMISSION_REMUNERATION = CHANGE.OK_PRINCIPLE_COMMISSION_REMUNERATION,
            DIM.EVALUATION_GLOBALE = CHANGE.EVALUATION_GLOBALE,
            DIM.CANDIDAT_ACTUELLEMENT_EN_POSTE = CHANGE.CANDIDAT_ACTUELLEMENT_EN_POSTE,
            DIM.DO_YOU_MEET_THE_LEGAL_AGE = CHANGE.DO_YOU_MEET_THE_LEGAL_AGE,
            DIM.DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK = CHANGE.DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
            DIM.ARE_YOU_CURRENTLY_EMPLOYED = CHANGE.ARE_YOU_CURRENTLY_EMPLOYED,
            DIM.ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK = CHANGE.ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
            DIM.WHAT_IS_YOUR_POSTAL_CODE = CHANGE.WHAT_IS_YOUR_POSTAL_CODE,
            DIM.ARE_YOU_OK_WITH_WORK_TIMINGS = CHANGE.ARE_YOU_OK_WITH_WORK_TIMINGS,
            DIM.CANDIDATE_SCORE = CHANGE.CANDIDATE_SCORE,
            DIM.SALES_OR_CUSTOMER_FACING_EXPERIENCE = CHANGE.SALES_OR_CUSTOMER_FACING_EXPERIENCE,
            DIM.DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE = CHANGE.DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
            DIM.OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS = CHANGE.OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
            DIM.SCHEDULE_START_DATE = CHANGE.SCHEDULE_START_DATE,
            DIM.EMAILPRIMARYHOME = CHANGE.EMAILPRIMARYHOME,
            DIM.EMAILPRIMARYWORK = CHANGE.EMAILPRIMARYWORK,
            DIM.REFERRALDATE = CHANGE.REFERRALDATE,
            DIM.INTERNAL = CHANGE.INTERNAL,
            DIM.TAGS_PHENOM = CHANGE.TAGS_PHENOM,
            DIM.POSTAL_CODE_OTHER_KILLER_QUESTIONS = CHANGE.POSTAL_CODE_OTHER_KILLER_QUESTIONS,
            DIM.WHAT_IS_THE_CANDIDATE_GENDER = CHANGE.WHAT_IS_THE_CANDIDATE_GENDER,
            DIM.WHAT_IS_THE_WORK_PERMIT_TYPE = CHANGE.WHAT_IS_THE_WORK_PERMIT_TYPE,
            DIM.YEAR_OF_EXPERIENCE_ROLE = CHANGE.YEAR_OF_EXPERIENCE_ROLE,
            DIM.BONUS = CHANGE.BONUS,
            DIM.TOOLS = CHANGE.TOOLS,
            DIM.ES_MOTIVATION = CHANGE.ES_MOTIVATION,
            DIM.ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE = CHANGE.ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
            DIM.DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE = CHANGE.DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE,
            DIM.SQ_EXECUTION_ID = CHANGE.SQ_EXECUTION_ID,
            DIM.SQ_ROW_HASH_T1 = CHANGE.SQ_ROW_HASH_T1
         FROM DB_WORKDAY.SH_MAIN.AUX_CANDIDATE_CHANGES CHANGE
            WHERE CHANGE.SQ_EXECUTION_ID = :VAR_EXECUTION AND
            DIM.IDCANDIDATES = CHANGE.IDCANDIDATES AND
            CHANGE.SQ_OPERATION_ID = 2 ;
            
            -- Update tyoe 1     

    -- Insert new records or new version 

        INSERT INTO DB_WORKDAY.SH_MAIN.DIM_CANDIDATE (
            IDCANDIDATES,
            IDCANDIDATE,
            CANDIDATEFULLNAME,
            CANDIDATEAGE,
            CANDIDATEEMAIL,
            CANDIDATEPHONE,
            CANDIDATECITY,
            CANDIDATETAGS,
            CANDIDATEPOOLS,
            COUNTRY,
            FROMDATE,
            TODATE,
            SQ_ROW_HASH_T1,           
            SQ_EXECUTION_ID,
            SQ_EXECUTION_ID_INSERTED,
            SQ_OPERATION_ID, 
            GENDER,
            ISPURGED,
            CURRENT_COMPANY,
            SKILL,
            HIRING_STATUS,
            PREFERRED_CATEGORY,
            PREFERRED_LOCATION,
            NOTES,
            "INTERNAL_EXTERNAL",
            LEAD_SOURCE,
            LANGUAGE,
            "DEGREE_CERTIFICATE",
            "MAJOR_FIELD_OF_STUDY",
            UNIVERSITY,
            CURRENT_OR_PAST_COMPANIES,
            CURRENT_OR_PAST_JOB_TITLES,
            CURRENT_OR_PAST_JOB_LOCATIONS,
            UTM_MEDIUM,
            UTM_CAMPAIGN,
            ZIPCODE,
            HIGHEST_EDUCATION,
            EDUCATION_START_DATE,
            EDUCATION_END_DATE,
            CANDIDATE_PREFERRED_LOCATION,
            AVAILABILITY_TO_START,
            SALARY_EXPECTATIONS,
            CURRENT_SALARY,
            YEARS_OF_EXPERIENCE,
            LOCAL_LANGUAGE_LEVEL,
            "CONTRACTOR_PROFILE_RECRUITERFILLS",
            CUSTOMER_SERVICE_EXPERIENCE,
            CURRENT_BENEFITS,
            CLEAN_CRIMINAL_RECORD,
            EXPERIENCE_IN_THE_AREA,
            PREFERRED_SHIFT,
            OWN_VEHICLE,
            FLEXIBLE_HOURS,
            CURRENTLY_EMPLOYED,
            SALES_EXPERIENCE,
            DRIVERS_LICENSE,
            MOTIVATION,
            PREFERRED_WORK_SCHEDULE,
            POSTAL_CODE,
            DRIVING_LICENSE,
            YEARS_SALES_EXPERIENCE,
            "CAR_RECRUITERFILLS",
            SALES_EXPERIENCE_TYPE,
            SHIFT_AVAILABILITY_HOURS,
            ENGLISH_LEVEL,
            TEAM_MANAGEMENT_EXPERIENCE,
            SELF_PROFILE_CONSIDERATION,
            MOBILITY,
            WORK_PERMIT,
            "INFORMATIONAL_GROUPING_NORDICS",
            "INFORMATIONAL_GROUPING_PERU",
            "INFORMATIONAL_GROUPING_PERU_KILL",
            "INFORMATIONAL_GROUPING_ARGENTINA",
            ASSESSMENT,
            ASSESSMENT_TOTAL_SCORE,
            SHIFT_AVAILABILITY_DAYS,
            MEET_LEGAL_AGE_REQUIREMENT,
            COLD_CANVASSING,
            HOW_DID_YOU_HEAR_ABOUT_US,
            LAST_EMAIL_RESPONSE,
            LAST_EMAIL_SENT,
            PRIMARY_NATIONALITY,
            TIMES_CALLED_CANDIDATE,
            REFERRER,
            "COLD_CANVASSING_RECRUITER_FILLS",
            EDUCATION_LEVEL,
            WORK_PERMIT_RECRUITER_FILLS,
            MOBILITY_RECRUITER_FILLS,
            CODE_POSTAL_CANDIDATE,
            TITULAIRE_DU_PERMIS_B,
            PERSON_VEHICLE,
            CLEAN_RECORD,
            WHEN_ARE_YOU_AVAILABLE,
            AVAILABLE_EVENINGANDSATURDAYS,
            OK_PRINCIPLE_COMMISSION_REMUNERATION,
            EVALUATION_GLOBALE,
            EMAILPRIMARYHOME,
            EMAILPRIMARYWORK,
            REFERRALDATE,
            CANDIDAT_ACTUELLEMENT_EN_POSTE,
            DO_YOU_MEET_THE_LEGAL_AGE,
            DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
            ARE_YOU_CURRENTLY_EMPLOYED,
            ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
            WHAT_IS_YOUR_POSTAL_CODE,
            ARE_YOU_OK_WITH_WORK_TIMINGS,
            CANDIDATE_SCORE,
            SALES_OR_CUSTOMER_FACING_EXPERIENCE,
            DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
            OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
            SCHEDULE_START_DATE,
            INTERNAL,
            TAGS_PHENOM,
            POSTAL_CODE_OTHER_KILLER_QUESTIONS,
            WHAT_IS_THE_CANDIDATE_GENDER,
            WHAT_IS_THE_WORK_PERMIT_TYPE,
            YEAR_OF_EXPERIENCE_ROLE,
            BONUS,
            TOOLS,
            ES_MOTIVATION,
            ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
            DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE
        )
             SELECT 
                IDCANDIDATES,
                IDCANDIDATE,
                CANDIDATEFULLNAME,
                CANDIDATEAGE,
                CANDIDATEEMAIL,
                CANDIDATEPHONE,
                CANDIDATECITY,
                CANDIDATETAGS,
                CANDIDATEPOOLS,
                COUNTRY,
                FROMDATE,
                TODATE,
                SQ_ROW_HASH_T1,
                SQ_EXECUTION_ID,
                SQ_EXECUTION_ID_INSERTED,
                SQ_OPERATION_ID, 
                GENDER,
                ISPURGED,
                CURRENT_COMPANY,
                SKILL,
                HIRING_STATUS,
                PREFERRED_CATEGORY,
                PREFERRED_LOCATION,
                NOTES,
                "INTERNAL_EXTERNAL",
                LEAD_SOURCE,
                LANGUAGE,
                "DEGREE_CERTIFICATE",
                "MAJOR_FIELD_OF_STUDY",
                UNIVERSITY,
                CURRENT_OR_PAST_COMPANIES,
                CURRENT_OR_PAST_JOB_TITLES,
                CURRENT_OR_PAST_JOB_LOCATIONS,
                UTM_MEDIUM,
                UTM_CAMPAIGN,
                ZIPCODE,
                HIGHEST_EDUCATION,
                EDUCATION_START_DATE,
                EDUCATION_END_DATE,
                CANDIDATE_PREFERRED_LOCATION,
                AVAILABILITY_TO_START,
                SALARY_EXPECTATIONS,
                CURRENT_SALARY,
                YEARS_OF_EXPERIENCE,
                LOCAL_LANGUAGE_LEVEL,
                "CONTRACTOR_PROFILE_RECRUITERFILLS",
                CUSTOMER_SERVICE_EXPERIENCE,
                CURRENT_BENEFITS,
                CLEAN_CRIMINAL_RECORD,
                EXPERIENCE_IN_THE_AREA,
                PREFERRED_SHIFT,
                OWN_VEHICLE,
                FLEXIBLE_HOURS,
                CURRENTLY_EMPLOYED,
                SALES_EXPERIENCE,
                DRIVERS_LICENSE,
                MOTIVATION,
                PREFERRED_WORK_SCHEDULE,
                POSTAL_CODE,
                DRIVING_LICENSE,
                YEARS_SALES_EXPERIENCE,
                "CAR_RECRUITERFILLS",
                SALES_EXPERIENCE_TYPE,
                SHIFT_AVAILABILITY_HOURS,
                ENGLISH_LEVEL,
                TEAM_MANAGEMENT_EXPERIENCE,
                SELF_PROFILE_CONSIDERATION,
                MOBILITY,
                WORK_PERMIT,
                "INFORMATIONAL_GROUPING_NORDICS",
                "INFORMATIONAL_GROUPING_PERU",
                "INFORMATIONAL_GROUPING_PERU_KILL",
                "INFORMATIONAL_GROUPING_ARGENTINA",
                ASSESSMENT,
                ASSESSMENT_TOTAL_SCORE,
                SHIFT_AVAILABILITY_DAYS,
                MEET_LEGAL_AGE_REQUIREMENT,
                COLD_CANVASSING,
                HOW_DID_YOU_HEAR_ABOUT_US,
                LAST_EMAIL_RESPONSE,
                LAST_EMAIL_SENT,
                PRIMARY_NATIONALITY,
                TIMES_CALLED_CANDIDATE,
                REFERRER,
                "COLD_CANVASSING_RECRUITER_FILLS",
                EDUCATION_LEVEL,
                WORK_PERMIT_RECRUITER_FILLS,
                MOBILITY_RECRUITER_FILLS,
                CODE_POSTAL_CANDIDATE,
                TITULAIRE_DU_PERMIS_B,
                PERSON_VEHICLE,
                CLEAN_RECORD,
                WHEN_ARE_YOU_AVAILABLE,
                AVAILABLE_EVENINGANDSATURDAYS,
                OK_PRINCIPLE_COMMISSION_REMUNERATION,
                EVALUATION_GLOBALE,
                EMAILPRIMARYHOME,
                EMAILPRIMARYWORK,
                REFERRALDATE,
                CANDIDAT_ACTUELLEMENT_EN_POSTE,
                DO_YOU_MEET_THE_LEGAL_AGE,
                DO_YOU_HAVE_THE_RIGHT_TO_WORK_IN_THE_UK,
                ARE_YOU_CURRENTLY_EMPLOYED,
                ARE_YOU_OK_WITH_US_CONDUCTING_A_DBS_CHECK,
                WHAT_IS_YOUR_POSTAL_CODE,
                ARE_YOU_OK_WITH_WORK_TIMINGS,
                CANDIDATE_SCORE,
                SALES_OR_CUSTOMER_FACING_EXPERIENCE,
                DO_YOU_HAVE_A_FULL_UK_DRIVING_LICENCE,
                OWN_CAR_AVAILABLE_FOR_FIRST_4_MONTHS,
                SCHEDULE_START_DATE,
                INTERNAL,
                TAGS_PHENOM,
                POSTAL_CODE_OTHER_KILLER_QUESTIONS,
                WHAT_IS_THE_CANDIDATE_GENDER,
                WHAT_IS_THE_WORK_PERMIT_TYPE,
                YEAR_OF_EXPERIENCE_ROLE,
                BONUS,
                TOOLS,
                ES_MOTIVATION,
                ETES_VOUS_A_LAISE_AVEC_LE_PORTE_A_PORTE,
                DISPOSITION_A_TRAVAILLER_UNE_BASE_DE_REMUNERATION_VARIABLE 
            FROM DB_WORKDAY.SH_MAIN.AUX_CANDIDATE_CHANGES CHANGE
            WHERE CHANGE.SQ_EXECUTION_ID = :VAR_EXECUTION AND
              CHANGE.SQ_OPERATION_ID IN (1
                                            );   
       
    
    -- Get statistics for current execution

        -- Get inserted Values
        
        SELECT MAX(total) INTO :VAR_INSERTED
        FROM (
            SELECT COUNT(*) AS total
            FROM DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
            WHERE SQ_OPERATION_ID = 1
              AND SQ_EXECUTION_ID = :VAR_EXECUTION
        );

        -- Get Updated values

        SELECT MAX(total) INTO :VAR_UPDATED
        FROM (
            SELECT COUNT(*) AS total
            FROM DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
            WHERE SQ_OPERATION_ID IN (2
                                        )
              AND SQ_EXECUTION_ID = :VAR_EXECUTION
        );

        -- Get deleted Values

        SELECT MAX(total) INTO :VAR_DELETED
        FROM (
            SELECT COUNT(*) AS total
            FROM DB_WORKDAY.SH_MAIN.DIM_CANDIDATE
            WHERE SQ_OPERATION_ID = 4
              AND SQ_EXECUTION_ID = :VAR_EXECUTION
        );

        -- Write succesfull Log 
        
        UPDATE DB_WORKDAY.SH_MAIN.AUX_CONTROL_LOAD_INFO 
        SET DS_STATUS = 'FINISH',
            DT_END_TIME = CURRENT_TIMESTAMP,
            QT_INSERTED = :VAR_INSERTED,
            QT_UPDATED = :VAR_UPDATED,
            QT_DELETED = :VAR_DELETED
        WHERE DS_TARGET_TABLE_NAME = 'DIM_CANDIDATE'
          AND DS_STATUS = 'STARTED'
          AND ID = :VAR_EXECUTION;

        RETURN 'FINISH';



EXCEPTION
    WHEN OTHER THEN


        VAR_DS_MESSAGE :=  SQLERRM;
    
        -- Write Log when process finish with errors
        
        UPDATE DB_WORKDAY.SH_MAIN.AUX_CONTROL_LOAD_INFO 
        SET DS_STATUS = 'ERROR',
            DT_END_TIME = CURRENT_TIMESTAMP,
            DS_MESSAGE = :VAR_DS_MESSAGE
        WHERE DS_TARGET_TABLE_NAME = 'DIM_CANDIDATE'
          AND DS_STATUS = 'STARTED'
          AND ID = :VAR_EXECUTION;

        RETURN 'ERROR '  ||  :VAR_DS_MESSAGE ;
     
END;



